; Hardware

; MCU: Raspberry Pi Pico / Pico W (RP2040)
; Sensor: IIS3DWB (STM)
; Interface: SPI (Mode 3)
; ODR: 26.7 kHz (aprox. “26 kHz”)
; Teste mecânico: microventilador gerando vibração na mesa

; Software

; Framework: Arduino (core mbed do RP2040)
; IDE: VS Code + PlatformIO
; Saída: Serial (USB)

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
monitor_speed = 115200
; forçando a geração do .uf2
upload_protocol = mbed   
[env:rpipicow]
; alterando de pico para rpipicow:
board = rpipicow
